# -*- coding: utf-8 -*-
"""CREDIT CARD FRAUD DECTECTION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIDJRCvCIU_GTDRAwiwpR6W6AycmBXu6
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv("creditcard.csv")
df.head()

print("Shape:", df.shape)
print("\nClass distribution:\n", df['Class'].value_counts())

X = df.drop('Class', axis=1)
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

print("Model training completed ")

y_pred = model.predict(X_test)
print(y_pred[:10])

print("Accuracy:", accuracy_score(y_test, y_pred))

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("Classification Report:\n", classification_report(y_test, y_pred))

new_data = X_test.iloc[0].values.reshape(1, -1)

prediction = model.predict(new_data)

if prediction[0] == 1:
    print("🚨 Fraud Transaction")
else:
    print("✅ Normal Transaction")